# Workflow name
name: 'Chromatic Deployment Of GyeongHoWebComponents Subproject'

# Event for the workflow
on:
  push:
    branches:
      - main

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - run: npm i
      - run: npm run lint
        #👇 Adds Chromatic as a step in the workflow
      - uses: chromaui/action@latest
        # Options required for Chromatic's GitHub Action
        with:
          #👇 Chromatic projectToken, see https://storybook.js.org/tutorials/intro-to-storybook/react/ko/deploy/ to obtain it
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: packages/gyeongho-web-components
          token: ${{ secrets.GITHUB_TOKEN }}
